[package]
name = "pairing"

# Remember to change version string in README.md.
version = "0.14.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
license = "MIT/Apache-2.0"

description = "Pairing-friendly elliptic curve library"
documentation = "https://docs.rs/pairing/"
homepage = "https://github.com/ebfull/pairing"
repository = "https://github.com/ebfull/pairing"

[dependencies]
blake2 = "0.7"
rand = { version = "0.4", default-features = false }
byteorder = { version = "1", default-features = false }

[features]
unstable-features = ["expose-arith"]
expose-arith = []
u128-support = []
std = []
default = ["std"]
